{
    'name': 'Association Template',
    'version': '16.0.0.0.1',
    'author': 'Mohamed Bekir',
    'license': 'LGPL-3',
    'category': 'Documentation',
    'depends': [
        'base',
        'mail',
        'website',
    ],
    'data': [
        'data/association.xml',
        'data/fonction_ecole_data.xml',
        'data/type_ecole_data.xml',
        'data/niveau_ecole_data.xml',
        'data/ief_data.xml',
        'data/type_besoins_data.xml',
        'data/mail_template.xml',
        'security/ir.model.access.csv',
        'views/association_template_view.xml',
        'views/fonction_ecole_view.xml',
        'views/type_ecole_view.xml',
        'views/niveau_ecole_view.xml',
        'views/ief_ecole_view.xml',
        'views/type_besoins_view.xml',
        'views/web_form_view.xml',
    ],
    'application': True,
}
